### ISSUE TITLE
Cookie is not allowed

### ISSUE THREAD

**Issue by joshhopkins** [nhost/nhost-js-sdk#49]
When running the latest docker image, with default config `COOKIE_SECURE, COOKIE_SAME_SITE`, I get the following response when calling `auth.login(email, password)`.

```
{"statusCode":400,"error":"Bad Request","message":"\"cookie\" is not allowed"}
```

Have tried both `use_cookies: false` and without the param:
```
const config = {
    base_url: process.env.REACT_APP_BACKEND_ENDPOINT,
    use_cookies: false,
}
```

Anything obvious I may be missing?

**Comment by Svarto** [comment]
Are you trying to instantiate the nhost-js-sdk in the nhost custom api container? Are you self hosting HBP (is that what you mean with docker)? And which version of nhost-js-sdk?

**Comment by joshhopkins** [comment]
> Are you trying to instantiate the nhost-js-sdk in the nhost custom api container?

I'm not familiar with the nhost custom api container, as in [this](https://hub.docker.com/r/nhost/nodeapi) container? I'm running [this](https://hub.docker.com/layers/nhost/hasura-backend-plus/sha-75e5572/images/sha256-4fbe5defa2f5259c46b39365a7605b59f65c569ba1a2bc9fda3bf5fd3ba95b2b?context=explore) image.

> Are you self hosting HBP (is that what you mean with docker)?

Yes, testing locally.

> And which version of nhost-js-sdk?

Latest version of nhost-js-sdk – 2.3.4.

**Comment by Svarto** [comment]
I ran into this problem recently and got it fixed by upgrading to v3.0.0 nhost-js-sdk AND HBP v.2.2.4. Try it and maybe it works for you too?

**Comment by joshhopkins** [comment]
Thanks for the update @Svarto. I'm still getting the same response after updating to `nhost-js-sdk` v3.0.0 + `HBP` v.2.2.4 (tried both docker image and source). 

It doesn't seem to be related to this library as `"\"cookie\" is not allowed"` is thrown when calling POST `/auth/login`.

I had a quick look [here](https://github.com/nhost/hasura-backend-plus/blob/0c030d7bc1672f02e5fcf04d11687cff3e92c23d/src/shared/validation.ts#L112) at it appears that there something odd going on with validation. See output:
```
[Error [ValidationError]: "cookie" is not allowed] {
  _original: { cookie: true },
  details: [
    {
      message: '"cookie" is not allowed',
      path: [Array],
      type: 'object.unknown',
      context: [Object]
    }
  ]
}
```

I also tried updating to the latest version of Joi (current package has been depreciated), with no luck.

**Comment by nunopato** [comment]
@joshhopkins if you explicitly set `useCookies: false` (for v3 note it is `camelCase`) you still get that error?

```js
const nhostClient = createClient({
  baseURL: 'https://backend-url.nhost.app',
  useCookies: false,
})
```

**Comment by joshhopkins** [comment]
Yes @nunopato – but I'm quite sure it's related to [this](https://github.com/nhost/hasura-backend-plus/issues/414#issuecomment-792190692).

**Comment by elitan** [comment]
@joshhopkins Can you just double-check your HBP version? Do you self-host or use Nhost?

I tried this exact setup and everything is working for me.

**Comment by aaronhayes** [comment]
I can confirm upgrading my docker version from `nhost/hasura-backend-plus:v2.2.1` to `nhost/hasura-backend-plus:v2.2.4` fixed this exact issue.

**Comment by elitan** [comment]
I'll close this for now since upgrading seems to fix the issue.
